### ISSUE TITLE
NG: UnreadablePostError when updating a person in the admin

### ISSUE THREAD

**Issue by mhl** [mysociety/pombola#1433]
We got 8 of these errors in quick succession about 1pm on Wed, 21 May 2014. (I've edited the request information to remove anything potentially identifying.)

    Traceback (most recent call last):
    
      File "/data/vhost/www.shineyoureye.org/pombola-virtualenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 107, in get_response
        response = middleware_method(request, callback, callback_args, callback_kwargs)
    
      File "/data/vhost/www.shineyoureye.org/pombola-virtualenv/lib/python2.7/site-packages/django/middleware/csrf.py", line 170, in process_view
        request_csrf_token = request.POST.get('csrfmiddlewaretoken', '')
    
      File "/data/vhost/www.shineyoureye.org/pombola-virtualenv/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 146, in _get_post
        self._load_post_and_files()
    
      File "/data/vhost/www.shineyoureye.org/pombola-virtualenv/lib/python2.7/site-packages/django/http/request.py", line 215, in _load_post_and_files
        self._post, self._files = self.parse_file_upload(self.META, data)
    
      File "/data/vhost/www.shineyoureye.org/pombola-virtualenv/lib/python2.7/site-packages/django/http/request.py", line 180, in parse_file_upload
        return parser.parse()
    
      File "/data/vhost/www.shineyoureye.org/pombola-virtualenv/lib/python2.7/site-packages/django/http/multipartparser.py", line 140, in parse
        for item_type, meta_data, field_stream in Parser(stream, self._boundary):
    
      File "/data/vhost/www.shineyoureye.org/pombola-virtualenv/lib/python2.7/site-packages/django/http/multipartparser.py", line 598, in __iter__
        for sub_stream in boundarystream:
    
      File "/data/vhost/www.shineyoureye.org/pombola-virtualenv/lib/python2.7/site-packages/django/utils/six.py", line 473, in next
        return type(self).__next__(self)
    
      File "/data/vhost/www.shineyoureye.org/pombola-virtualenv/lib/python2.7/site-packages/django/http/multipartparser.py", line 415, in __next__
        return LazyStream(BoundaryIter(self._stream, self._boundary))
    
      File "/data/vhost/www.shineyoureye.org/pombola-virtualenv/lib/python2.7/site-packages/django/http/multipartparser.py", line 441, in __init__
        unused_char = self._stream.read(1)
    
      File "/data/vhost/www.shineyoureye.org/pombola-virtualenv/lib/python2.7/site-packages/django/http/multipartparser.py", line 315, in read
        out = b''.join(parts())
    
      File "/data/vhost/www.shineyoureye.org/pombola-virtualenv/lib/python2.7/site-packages/django/http/multipartparser.py", line 308, in parts
        chunk = next(self)
    
      File "/data/vhost/www.shineyoureye.org/pombola-virtualenv/lib/python2.7/site-packages/django/utils/six.py", line 473, in next
        return type(self).__next__(self)
    
      File "/data/vhost/www.shineyoureye.org/pombola-virtualenv/lib/python2.7/site-packages/django/http/multipartparser.py", line 330, in __next__
        output = next(self._producer)
    
      File "/data/vhost/www.shineyoureye.org/pombola-virtualenv/lib/python2.7/site-packages/django/utils/six.py", line 473, in next
        return type(self).__next__(self)
    
      File "/data/vhost/www.shineyoureye.org/pombola-virtualenv/lib/python2.7/site-packages/django/http/multipartparser.py", line 391, in __next__
        data = self.flo.read(self.chunk_size)
    
      File "/data/vhost/www.shineyoureye.org/pombola-virtualenv/lib/python2.7/site-packages/django/http/request.py", line 244, in read
        six.reraise(UnreadablePostError, UnreadablePostError(*e.args), sys.exc_info()[2])
    
      File "/data/vhost/www.shineyoureye.org/pombola-virtualenv/lib/python2.7/site-packages/django/http/request.py", line 242, in read
        return self._stream.read(*args, **kwargs)
    
      File "/data/vhost/www.shineyoureye.org/pombola-virtualenv/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 51, in read
        result = self.buffer + self._read_limited(size - len(self.buffer))
    
      File "/data/vhost/www.shineyoureye.org/pombola-virtualenv/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 39, in _read_limited
        result = self.stream.read(size)
    
    UnreadablePostError: request data read error
    
    
    <WSGIRequest
    path:/admin/core/person/38/,
    GET:<QueryDict: {u'_changelist_filters': [u'q=adetunbi']}>,
    POST:<could not parse>,
    META:{'CONTENT_LENGTH': '24603',
     'CONTENT_TYPE': 'multipart/form-data; boundary=----WebKitFormBoundarygcsVPEwlrBn0gjs3',
     'DOCUMENT_ROOT': '/data/vhost/www.shineyoureye.org/docs',
     'GATEWAY_INTERFACE': 'CGI/1.1',
     'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
     'HTTP_ACCEPT_ENCODING': 'gzip',
     'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.8',
     'HTTP_CACHE_CONTROL': 'max-age=0',
     'HTTP_HOST': 'www.shineyoureye.org',
     'HTTP_ORIGIN': 'http://www.shineyoureye.org',
     'HTTP_REFERER': 'http://www.shineyoureye.org/admin/core/person/38/?_changelist_filters=q%3Dadetunbi',
     'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.154 Safari/537.36',

**Comment by mhl** [comment]
There's a helpful example of how to just filter out `UnreadablePostError`s in the Django docs:

https://docs.djangoproject.com/en/1.6/topics/logging/#django.utils.log.CallbackFilter
