### ISSUE TITLE
rebuild_index causes stack trace in elasticsearch log

### ISSUE THREAD

**Issue by Flupsy** [mysociety/pombola#1584]
I'm running `rebuild_index` as part of mzalendo's move to pluto, and this appeared in `/var/log/elasticsearch/elasticsearch.log` at the start of the job:

````
[2014-12-19 13:34:00,253][DEBUG][action.index             ] [Matt Murdock] [mzalendo][2], node[GotL2dmUQHmAI3kJFSl3VA], [P], s[STARTED]: Failed to execute [index {[mzalendo][_mapping][modelresult], source[{"modelresult": {"_boost": {"name": "boost", "null_value": 1.0}, "properties": {"django_id": {"include_in_all": false, "index": "not_analyzed", "type": "string"}, "text": {"type": "string", "analyzer": "snowball"}, "kind": {"type": "string", "analyzer": "snowball"}, "django_ct": {"include_in_all": false, "index": "not_analyzed", "type": "string"}, "name_auto": {"type": "string", "analyzer": "edgengram_analyzer"}, "hidden": {"type": "boolean"}}}}]}]
org.elasticsearch.indices.InvalidTypeNameException: mapping type name [_mapping] can't start with '_'
        at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:202)
        at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:190)
        at org.elasticsearch.index.mapper.MapperService.documentMapperWithAutoCreate(MapperService.java:409)
        at org.elasticsearch.index.shard.service.InternalIndexShard.prepareIndex(InternalIndexShard.java:328)
        at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:203)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.performOnPrimary(TransportShardReplicationOperationAction.java:521)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction$1.run(TransportShardReplicationOperationAction.java:419)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:701)
````

**Comment by mhl** [comment]
@dracos Is there any documentation or reference we could look at for how to rebuild the index with Haystack / Elasticsearch with zero downtime, as you suggest?

**Comment by dracos** [comment]
The two scripts SayIt uses are https://github.com/mysociety/sayit/blob/master/speeches/management/commands/sayit_search_new_index.py and https://github.com/mysociety/sayit/blob/master/speeches/management/commands/sayit_search_make_index_live.py. There's a comment with brief summary on https://github.com/mysociety/sayit/issues/299 that's still awaiting being expanded. But in summary, you create a timestamped database (`foo_timestamp`), and aliases `foo` and `foo_write` pointing at that database. Your `HAYSTACK_CONNECTIONS` has two entries, for `foo` and `foo_write`, like https://github.com/mysociety/sayit.mysociety.org/blob/master/sayit_mysociety_org/settings/base.py#L232-L243 . You use the default alias for reading, the write alias for writing. To update the entire database, you create a new timestamped database and change the write alias (first script). Build, then run the second script to change the read alias.

```
$ curl http://localhost:9200/_aliases?pretty
[…]
  "sayit_2014-01-17t18:26:48.142321" : {
    "aliases" : {
      "sayit_write" : { },
      "sayit" : { }
    }
  },
[…]
```
