### ISSUE TITLE
fix update_za_hansard.bash

### ISSUE THREAD

**Issue by mhl** [mysociety/pombola#1595]
This is currently failing in the `init_popit_data()` of `popit_resolver_init`:

```
Done 1008 out of 6865 people (14%)
Done 1009 out of 6865 people (14%)
Done 1010 out of 6865 people (14%)
Done 1011 out of 6865 people (14%)
Done 1012 out of 6865 people (14%)
Traceback (most recent call last):
  File "./manage.py", line 50, in <module>
    execute_from_command_line(sys.argv)
  File "/data/vhost/www.pa.org.za/pombola-virtualenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/data/vhost/www.pa.org.za/pombola-virtualenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/data/vhost/www.pa.org.za/pombola-virtualenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/data/vhost/www.pa.org.za/pombola-virtualenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/data/vhost/www.pa.org.za/pombola-virtualenv/local/lib/python2.7/site-packages/popit_resolver/management/commands/popit_resolver_init.py", line 27, in handle
    se.init_popit_data()
  File "/data/vhost/www.pa.org.za/pombola-virtualenv/local/lib/python2.7/site-packages/popit_resolver/resolve.py", line 230, in init_popit_data
    organization = organizations[m['organization_id']]
KeyError: 'organization_id'
```

**Comment by mhl** [comment]
Fixed in a40ef30eee938a28a9996f24b3d03204d6a4b9a4 and https://github.com/mysociety/popit-resolver/commit/357e1414e7c7dbeb0946b4c173a7a28f8acd6806

I had hoped that this was all there was to https://github.com/mysociety/pombola/issues/1597 but that's still an issue.
