### ISSUE TITLE
Error at `/election/2014/national/province/eastern-cape/`

### ISSUE THREAD

**Issue by duncanparkes** [mysociety/pombola#1765]
ERROR (EXTERNAL IP): Internal Server Error: /election/2014/national/province/eastern-cape/

```
Traceback (most recent call last):

  File "/data/vhost/www.pa.org.za/pombola-virtualenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/data/vhost/www.pa.org.za/pombola-virtualenv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)

  File "/data/vhost/www.pa.org.za/pombola-virtualenv/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)

  File "/data/vhost/www.pa.org.za/pombola-virtualenv/lib/python2.7/site-packages/django/views/generic/base.py", line 154, in get
    context = self.get_context_data(**kwargs)

  File "/data/vhost/www.pa.org.za/pombola/pombola/south_africa/views.py", line 1302, in get_context_data
    candidates = sorted(candidate_list, key=lambda x:

  File "/data/vhost/www.pa.org.za/pombola/pombola/south_africa/views.py", line 1303, in <lambda>
    int(re.match('\d+', x.title.name).group())

AttributeError: 'NoneType' object has no attribute 'name'
```

This looks related to #1660, which also mentions eastern-cape.

**Comment by duncanparkes** [comment]
Delete position for zukiswa-veronica-ncitha in anc-regional-eastern-cape-election-list-2014, which is clearly erroneous (it has a start date after the election).
