### ISSUE TITLE
[Django] ERROR (EXTERNAL IP): Internal Server Error: /election/2014/provincial/northern-cape/

### ISSUE THREAD

**Issue by duncanparkes** [mysociety/pombola#1783]
```
Traceback (most recent call last):

  File "/data/vhost/www.pa.org.za/pombola-virtualenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/data/vhost/www.pa.org.za/pombola-virtualenv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)

  File "/data/vhost/www.pa.org.za/pombola-virtualenv/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)

  File "/data/vhost/www.pa.org.za/pombola-virtualenv/lib/python2.7/site-packages/django/views/generic/base.py", line 154, in get
    context = self.get_context_data(**kwargs)

  File "/data/vhost/www.pa.org.za/pombola/pombola/south_africa/views.py", line 1302, in get_context_data
    candidates = sorted(candidate_list, key=lambda x:

  File "/data/vhost/www.pa.org.za/pombola/pombola/south_africa/views.py", line 1303, in <lambda>
    int(re.match('\d+', x.title.name).group())

AttributeError: 'NoneType' object has no attribute 'group'
```

Looks potentially related to #1765

**Comment by duncanparkes** [comment]
Delete two obviously erroneous positions.

``
mzalendo-za-production=> select start_date, core_position.id, core_organisation.slug, legal_name, title_id, core_positiontitle.slug from core_position inner join core_positiontitle on core_position.title_id = core_positiontitle.id inner join core_person on core_person.id = core_position.person_id inner join core_organisation on core_organisation.id = core_position.organisation_id where organisation_id in (select id from core_organisation where slug ~ 'northern-cape' and slug ~ 'election-list' and slug ~ 'anc') and core_positiontitle.slug = 'member';
 start_date |  id   |                      slug                       |  legal_name   | title_id |  slug  
------------+-------+-------------------------------------------------+---------------+----------+--------
 2015-00-00 | 70748 | anc-regional-northern-cape-election-list-2014   | Agnes Tuck    |      161 | member
 2015-00-00 | 70750 | anc-provincial-northern-cape-election-list-2014 | Joice Basson  |      161 | member
```

Both these positions start after the date of the election, and they don't appear on any candidate lists.
