### ISSUE TITLE
ZA - Traceback from autocomplete

### ISSUE THREAD

**Issue by duncanparkes** [mysociety/pombola#1803]
```
Traceback (most recent call last):

  File "/data/vhost/www.pa.org.za/pombola-virtualenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/data/vhost/www.pa.org.za/pombola/pombola/search/views.py", line 437, in autocomplete
    css_class = object.css_class()

AttributeError: 'NoneType' object has no attribute 'css_class'
```

**Comment by mhl** [comment]
This is because of https://github.com/mysociety/pombola/issues/1424

We haven't had these for a while, so I've committed and run a script to find stale Elasticsearch entries:

https://github.com/mysociety/pombola/blob/master/pombola/core/management/commands/core_find_stale_elasticsearch_documents.py

... and I'm running that on the server at the moment.

**Comment by mhl** [comment]
Output from that command, which indicates which objects (they happen to be of the Person model) are have been deleted from PostgreSQL but not Elasticsearch:

```
Checking pombola.core.models.Organisation (1313 objects in the database)
Checking pombola.core.models.Person (6967 objects in the database)
Checking pombola.core.models.Place (589 objects in the database)
      stale search entry for primary key 9318
      stale search entry for primary key 9325
      stale search entry for primary key 9317
      stale search entry for primary key 9324
      stale search entry for primary key 9323
Checking pombola.core.models.PositionTitle (444 objects in the database)
Checking pombola.info.models.InfoPage (556 objects in the database)
Checking popit_resolver.models.EntityName (97109 objects in the database)
Checking speeches.models.Section (203979 objects in the database)
Checking speeches.models.Speaker (10414 objects in the database)
Checking speeches.models.Speech (796668 objects in the database)
```

**Comment by mhl** [comment]
Fixed using `./manage.py core_find_stale_elasticsearch_documents --delete`
