### ISSUE TITLE
Traceback from update_hansard.bash

### ISSUE THREAD

**Issue by duncanparkes** [mysociety/pombola#1805]
Looks to me as though we just need to continue on a loop when no <a> is found, probably.

```
Traceback (most recent call last):
  File "./manage.py", line 50, in <module>
    execute_from_command_line(sys.argv)
  File "/data/vhost/mzalendo.mysociety.org/pombola-virtualenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/data/vhost/mzalendo.mysociety.org/pombola-virtualenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/data/vhost/mzalendo.mysociety.org/pombola-virtualenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/data/vhost/mzalendo.mysociety.org/pombola-virtualenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/data/vhost/mzalendo.mysociety.org/pombola-virtualenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 415, in handle
    return self.handle_noargs(**options)
  File "/data/vhost/mzalendo.mysociety.org/pombola/pombola/hansard/management/commands/hansard_check_for_new_sources.py", line 65, in handle_noargs
    self.process_url(list_page, url, verbose)
  File "/data/vhost/mzalendo.mysociety.org/pombola/pombola/hansard/management/commands/hansard_check_for_new_sources.py", line 90, in process_url
    for section in link_sections
AttributeError: 'NoneType' object has no attribute 'a'
```

**Comment by mhl** [comment]
Just a note to check that with this kind of error we always have a URL to retry so reproducing is easy...

**Comment by chrismytton** [comment]
No longer seeing this error.
