### ISSUE TITLE
httplib.ResponseNotReady from update_hansard.bash

### ISSUE THREAD

**Issue by duncanparkes** [mysociety/pombola#1806]
Uncaught error here from httplib - seems like something we should try catching and retrying.

```
Traceback (most recent call last):
  File "./manage.py", line 50, in <module>
    execute_from_command_line(sys.argv)
  File "/data/vhost/mzalendo.mysociety.org/pombola-virtualenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/data/vhost/mzalendo.mysociety.org/pombola-virtualenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/data/vhost/mzalendo.mysociety.org/pombola-virtualenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/data/vhost/mzalendo.mysociety.org/pombola-virtualenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/data/vhost/mzalendo.mysociety.org/pombola-virtualenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 415, in handle
    return self.handle_noargs(**options)
  File "/data/vhost/mzalendo.mysociety.org/pombola/pombola/hansard/management/commands/hansard_check_for_new_sources.py", line 65, in handle_noargs
    self.process_url(list_page, url, verbose)
  File "/data/vhost/mzalendo.mysociety.org/pombola/pombola/hansard/management/commands/hansard_check_for_new_sources.py", line 83, in process_url
    for soup, base_url in self.get_index_pages(url, list_page, verbose):
  File "/data/vhost/mzalendo.mysociety.org/pombola/pombola/hansard/management/commands/hansard_check_for_new_sources.py", line 174, in get_index_pages
    response, content = h.request(next_url)
  File "/data/vhost/mzalendo.mysociety.org/pombola-virtualenv/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1563, in request
    (response, new_content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/data/vhost/mzalendo.mysociety.org/pombola-virtualenv/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1335, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/data/vhost/mzalendo.mysociety.org/pombola-virtualenv/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1291, in _conn_request
    response = conn.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1022, in getresponse
    raise ResponseNotReady()
httplib.ResponseNotReady
```

**Comment by chrismytton** [comment]
No longer seeing this error.
