### ISSUE TITLE
ZA Traceback from attendance data

### ISSUE THREAD

**Issue by duncanparkes** [mysociety/pombola#1819]
We're finding more than one person in the PMG API with the same slug. This mustn't be allowed to cause tracebacks.

```Traceback (most recent call last):

  File "/data/vhost/www.pa.org.za/pombola-virtualenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/data/vhost/www.pa.org.za/pombola-virtualenv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)

  File "/data/vhost/www.pa.org.za/pombola-virtualenv/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)

  File "/data/vhost/www.pa.org.za/pombola/pombola/slug_helpers/views.py", line 31, in get
    return super(SlugRedirectMixin, self).get(request, *args, **kwargs)

  File "/data/vhost/www.pa.org.za/pombola-virtualenv/lib/python2.7/site-packages/django/views/generic/detail.py", line 111, in get
    context = self.get_context_data(object=self.object)

  File "/data/vhost/www.pa.org.za/pombola/pombola/south_africa/views.py", line 749, in get_context_data
    context['attendance'], context['latest_meetings_attended'] = self.get_attendance_data_for_display()

  File "/data/vhost/www.pa.org.za/pombola/pombola/south_africa/views.py", line 716, in get_attendance_data_for_display
    raw_data = self.download_attendance_data()

  File "/data/vhost/www.pa.org.za/pombola/pombola/south_africa/views.py", line 624, in download_attendance_data
    attendance_url = next_url = self.get_attendance_data_url()

  File "/data/vhost/www.pa.org.za/pombola/pombola/south_africa/views.py", line 618, in get_attendance_data_url
    identifier = self.store_or_get_pmg_member_id()

  File "/data/vhost/www.pa.org.za/pombola/pombola/south_africa/views.py", line 605, in store_or_get_pmg_member_id
    raise Exception('Duplicate members at PMG with slug {}'.format(self.object.slug))

Exception: Duplicate members at PMG with slug cassel-charlie-mathale
```

**Comment by duncanparkes** [comment]
As of 489e81f this should manifest itself as no attendance data tab rather than an error for the whole page.

**Comment by duncanparkes** [comment]
For now I'm going to leave this with @longhotsummer, who's checking up on the data from the PMG API.

**Comment by longhotsummer** [comment]
Our data no longer has duplicates and we're about to enforce that at the DB level in this pull request: https://github.com/Code4SA/pmg-cms-2/pull/88

**Comment by duncanparkes** [comment]
Fantastic - thanks!
