### ISSUE TITLE
output-on-error run_management_command kenya_assign_aspirants_to_coalitions

### ISSUE THREAD

**Issue by duncanparkes** [mysociety/pombola#2111]
```
Traceback (most recent call last):
  File "./manage.py", line 72, in <module>
    execute_from_command_line(sys.argv)
  File "/data/vhost/mzalendo.mysociety.org/pombola-virtualenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/data/vhost/mzalendo.mysociety.org/pombola-virtualenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/data/vhost/mzalendo.mysociety.org/pombola-virtualenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/data/vhost/mzalendo.mysociety.org/pombola-virtualenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/data/vhost/mzalendo.mysociety.org/pombola/pombola/kenya/management/commands/kenya_assign_aspirants_to_coalitions.py", line 224, in handle
    in coalition_party_slugs
  File "/data/vhost/mzalendo.mysociety.org/pombola-virtualenv/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/data/vhost/mzalendo.mysociety.org/pombola-virtualenv/local/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
pombola.core.models.DoesNotExist: Organisation matching query does not exist.
```

**Comment by tmtmtmtm** [comment]
Why is this script even running in the first place? This doesn't seem like something that should be running regularly (or is misnamed?)

**Comment by mhl** [comment]
There's not much discussion I can find about why this approach was taken, but it was introduced to fix this ticket:

* https://github.com/mysociety/pombola/issues/478

It would be better to model this now with `OrganisationRelationship` and `OrganisationRelationshipKind` as suggested here:

* https://github.com/mysociety/pombola/issues/1485

(You could also do it by adding a `parent` attribute to `Organisation` (to match Popolo), but it would be nice to have start and end dates for the coalition membership which would be easier to support with `OrganisationRelationship`.)

**Comment by tmtmtmtm** [comment]
@mhl my question was more to do with whether this should currently be running at all (distinct from questions about underlying implementation / modelling of coalitions etc). It seems like this could cause unexpected issues if it's silently changing data that admins add.

**Comment by mhl** [comment]
@tmtmtmtm I think you're right - we should disable this. Done in 1291768d43a75
