### ISSUE TITLE
[WriteInPublic] Error on non-contactable committees

### ISSUE THREAD

**Issue by chrismytton** [mysociety/pombola#2399]
When you visit the messages page of a committee that can't be contacted because it doesn't have an email address and therefore isn't in WriteInPublic the following error occurs:

```
Internal Server Error: /organisation/standing-committee-on-public-accounts/messages/ 
Traceback (most recent call last): 
  File "/data/vhost/www.pa.org.za/pombola-virtualenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response 
    response = wrapped_callback(request, *callback_args, **callback_kwargs) 
  File "/data/vhost/www.pa.org.za/pombola-virtualenv/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view 
    return self.dispatch(request, *args, **kwargs) 
  File "/data/vhost/www.pa.org.za/pombola/pombola/writeinpublic/views.py", line 141, in dispatch 
    return super(WriteInPublicMixin, self).dispatch(*args, **kwargs) 
  File "/data/vhost/www.pa.org.za/pombola-virtualenv/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch 
    return handler(request, *args, **kwargs) 
  File "/data/vhost/www.pa.org.za/pombola-virtualenv/lib/python2.7/site-packages/django/views/generic/base.py", line 158, in get 
    context = self.get_context_data(**kwargs) 
  File "/data/vhost/www.pa.org.za/pombola/pombola/writeinpublic/views.py", line 269, in get_context_data 
    context['messages'] = self.client.get_messages(uri) 
  File "/data/vhost/www.pa.org.za/pombola/pombola/writeinpublic/client.py", line 93, in get_messages 
    response.raise_for_status() 
  File "/data/vhost/www.pa.org.za/pombola-virtualenv/lib/python2.7/site-packages/requests/models.py", line 834, in raise_for_status 
    raise HTTPError(http_error_msg, response=self) 
HTTPError: 404 Client Error: NOT FOUND 
```

This is because the app makes a request for the messages to this "person" (AKA committee) and WiP returns a 404 because it doesn't recognise the person_id.

I think we should do two things:

1. Handle the `requests.HTTPError` properly
2. Don't link to the messages page for committees that can't be contacted.

**Comment by chrismytton** [comment]
Pull request for handling the error properly here: https://github.com/mysociety/pombola/pull/2400
