### ISSUE TITLE
Error running core_export_to_popolo_json via cron

### ISSUE THREAD

**Issue by chrismytton** [mysociety/pombola#2489]
We're seeing an error from the South Africa cron job which runs the `core_export_to_popolo_json` command.

```
Traceback (most recent call last):
  File "./manage.py", line 70, in <module>
    execute_from_command_line(sys.argv)
  File "/data/vhost/www.pa.org.za/pombola-virtualenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/data/vhost/www.pa.org.za/pombola-virtualenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/data/vhost/www.pa.org.za/pombola-virtualenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/data/vhost/www.pa.org.za/pombola-virtualenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/data/vhost/www.pa.org.za/pombola/pombola/core/management/commands/core_export_to_popolo_json.py", line 60, in handle
    inline_memberships=False
  File "/data/vhost/www.pa.org.za/pombola/pombola/core/popolo.py", line 364, in get_popolo_data
    inline_memberships,
  File "/data/vhost/www.pa.org.za/pombola/pombola/core/popolo.py", line 314, in get_people
    add_start_and_end_date(position, properties)
  File "/data/vhost/www.pa.org.za/pombola/pombola/core/popolo.py", line 124, in add_start_and_end_date
    properties[start_key_map[1]] = date_to_partial_iso8601(start_value)
  File "/data/vhost/www.pa.org.za/pombola/pombola/core/popolo.py", line 84, in date_to_partial_iso8601
    return d.strftime("%Y-%m-%d")
ValueError: year=171 is before 1900; the datetime strftime() methods require year >= 1900
```

**Comment by chrismytton** [comment]
Looks like [this position](https://www.pa.org.za/admin/core/position/72153/) for [Bentley Vass](https://www.pa.org.za/person/bentley-vass/) is causing the error because it has a `start_date` of `3rd October 171`.

That position record was created `2018-10-04 13:16:47.125748`, but there's no history in the admin, so it was created by something outside the Django admin.

**Comment by chrismytton** [comment]
Ah I think that position must have been created by `update_za_hansard.bash`, as that's set to run at 13:13 each day:

```
13 1 * * * mzalendo-south-africa output-on-error update_za_hansard.bash
```

**Comment by chrismytton** [comment]
Have fixed this in the database, so these error emails have stopped.
