### ISSUE TITLE
[KE] Investigate why Hansard isn't updating

### ISSUE THREAD

**Issue by chrismytton** [mysociety/pombola#2502]
From Jessica:

> it seems the hansard as posted by the National Assembly and Senated has not been synching with our system since August. That means we are behind by almost three months. Our users have noticed the error too. Kindly just check the entire system. This is really huge for us as we are starting to carry out research on the profiles for our Annual People's Shujaaz Awards

**Comment by chrismytton** [comment]
The error we're seeing is as follows:

```
Traceback (most recent call last): 
  File "./manage.py", line 70, in <module> 
    execute_from_command_line(sys.argv) 
  File "/data/vhost/mzalendo.mysociety.org/pombola-virtualenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line 
    utility.execute() 
  File "/data/vhost/mzalendo.mysociety.org/pombola-virtualenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute 
    self.fetch_command(subcommand).run_from_argv(self.argv) 
  File "/data/vhost/mzalendo.mysociety.org/pombola-virtualenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv 
    self.execute(*args, **cmd_options) 
  File "/data/vhost/mzalendo.mysociety.org/pombola-virtualenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute 
    output = self.handle(*args, **options) 
  File "/data/vhost/mzalendo.mysociety.org/pombola-virtualenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 661, in handle 
    return self.handle_noargs(**options) 
  File "/data/vhost/mzalendo.mysociety.org/pombola/pombola/hansard/management/commands/hansard_check_for_new_sources.py", line 62, in handle_noargs 
    self.process_url(list_page, url, verbose) 
  File "/data/vhost/mzalendo.mysociety.org/pombola/pombola/hansard/management/commands/hansard_check_for_new_sources.py", line 80, in process_url 
    for soup, base_url in self.get_index_pages(url, list_page, verbose): 
  File "/data/vhost/mzalendo.mysociety.org/pombola/pombola/hansard/management/commands/hansard_check_for_new_sources.py", line 182, in get_index_pages 
    next_url = self.get_next_url(soup, base_url) 
  File "/data/vhost/mzalendo.mysociety.org/pombola/pombola/hansard/management/commands/hansard_check_for_new_sources.py", line 196, in get_next_url 
    if next_page_button.a: 
AttributeError: 'NoneType' object has no attribute 'a' 
```

https://groups.google.com/a/mysociety.org/d/msg/mzalendo-managers/EMjCc4o9h-I/Z6UQS3XeBAAJ
