### ISSUE TITLE
[ZA] AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by chrismytton** [mysociety/pombola#2575]
Error on [this page](https://www.pa.org.za/election/2014/national/party/da/).

https://groups.google.com/a/mysociety.org/d/msg/cron-pa/rGnQ8VDqiGA/8D9zDW3aBAAJ

```
Internal Server Error: /election/2014/national/party/da/
Traceback (most recent call last):
  File "/data/vhost/www.pa.org.za/pombola-virtualenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/vhost/www.pa.org.za/pombola-virtualenv/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/data/vhost/www.pa.org.za/pombola-virtualenv/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/data/vhost/www.pa.org.za/pombola-virtualenv/lib/python2.7/site-packages/django/views/generic/base.py", line 158, in get
    context = self.get_context_data(**kwargs)
  File "/data/vhost/www.pa.org.za/pombola/pombola/south_africa/views/elections.py", line 225, in get_context_data
    key=lambda x: int(re.match('\d+', x.title.name).group())
  File "/data/vhost/www.pa.org.za/pombola/pombola/south_africa/views/elections.py", line 225, in <lambda>
    key=lambda x: int(re.match('\d+', x.title.name).group())
AttributeError: 'NoneType' object has no attribute 'group'

Request repr(): 
<WSGIRequest
path:/election/2014/national/party/da/,
GET:<QueryDict: {}>,
POST:<QueryDict: {}>,
COOKIES:{},
META:{u'CSRF_COOKIE': u'tSLUdrwyxidngq2fbSmNSVFYL0ZHJvgQ',
 'DOCUMENT_ROOT': '/data/vhost/www.pa.org.za/docs',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': '*/*',
 'HTTP_ACCEPT_ENCODING': 'gzip',
 'HTTP_ACCEPT_LANGUAGE': 'en-US',
 'HTTP_HOST': 'www.pa.org.za',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (compatible; Baiduspider/2.0; +http://www.baidu.com/search/spider.html)',
 'HTTP_X_FORWARDED_FOR': '180.76.15.23',
 'HTTP_X_FORWARDED_PROTO': 'https',
 'HTTP_X_REAL_IP': '180.76.15.23',
 'HTTP_X_VARNISH': '2149742615',
 'PATH_INFO': u'/election/2014/national/party/da/',
 'PATH_TRANSLATED': '/data/vhost/www.pa.org.za/pombola/pombola/wsgi.py/election/2014/national/party/da/',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '180.76.15.23',
 'REMOTE_PORT': '32976',
 'REQUEST_METHOD': 'GET',
 'REQUEST_URI': '/election/2014/national/party/da/',
 'SCRIPT_FILENAME': '/data/vhost/www.pa.org.za/pombola/pombola/wsgi.py',
 'SCRIPT_NAME': u'',
 'SCRIPT_URI': 'http://www.pa.org.za/election/2014/national/party/da/',
 'SCRIPT_URL': '/election/2014/national/party/da/',
 'SERVER_ADDR': '127.0.0.1',
 'SERVER_ADMIN': 'webmaster@pa.org.za',
 'SERVER_NAME': 'www.pa.org.za',
 'SERVER_PORT': '80',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SIGNATURE': '',
 'SERVER_SOFTWARE': 'Apache',
 'mod_wsgi.application_group': 'www.pa.org.za|',
 'mod_wsgi.callable_object': 'application',
 'mod_wsgi.handler_script': '',
 'mod_wsgi.input_chunked': '0',
 'mod_wsgi.listener_host': '127.0.0.1',
 'mod_wsgi.listener_port': '80',
 'mod_wsgi.process_group': 'www.pa.org.za',
 'mod_wsgi.request_handler': 'wsgi-script',
 'mod_wsgi.script_reloading': '1',
 'mod_wsgi.version': (3, 3),
 'wsgi.errors': <mod_wsgi.Log object at 0x7f6adbc7b070>,
 'wsgi.file_wrapper': <built-in method file_wrapper of mod_wsgi.Adapter object at 0x7f6ae4305b70>,
 'wsgi.input': <mod_wsgi.Input object at 0x7f6ade988830>,
 'wsgi.multiprocess': True,
 'wsgi.multithread': False,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 1)}>
```

**Comment by chrismytton** [comment]
This was caused by a data error. [Fezeka Mbiko](https://www.pa.org.za/person/fezeka-mbiko/) had a membership at "Democratic Alliance National Election List 2014" rather than "Democratic Alliance (DA) (Party)". I've fixed that in the admin and the page that was causing the error is working again now.
