### ISSUE TITLE
[KE] Hansard error: Failed to find the Venue

### ISSUE THREAD

**Issue by chrismytton** [mysociety/pombola#2583]
This error occurred on Friday morning (29th March). It came from the `update_hansard.bash` cron job.

```
There was an exception when parsing <open file '/data/vhost/mzalendo.mysociety.org/hansard_cache/3/9/02293', mode 'r' at 0x3835270>
Traceback (most recent call last):
  File "./manage.py", line 70, in <module>
    execute_from_command_line(sys.argv)
  File "/data/vhost/mzalendo.mysociety.org/pombola-virtualenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/data/vhost/mzalendo.mysociety.org/pombola-virtualenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/data/vhost/mzalendo.mysociety.org/pombola-virtualenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/data/vhost/mzalendo.mysociety.org/pombola-virtualenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/data/vhost/mzalendo.mysociety.org/pombola-virtualenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 661, in handle
    return self.handle_noargs(**options)
  File "/data/vhost/mzalendo.mysociety.org/pombola/pombola/hansard/management/commands/hansard_process_sources.py", line 29, in handle_noargs
    data = KenyaParser.convert_html_to_data( html )
  File "/data/vhost/mzalendo.mysociety.org/pombola/pombola/hansard/kenya_parser.py", line 367, in convert_html_to_data
    'meta': cls.extract_meta_from_transcript( meaningful_content ),
  File "/data/vhost/mzalendo.mysociety.org/pombola/pombola/hansard/kenya_parser.py", line 407, in extract_meta_from_transcript
    raise Exception, "Failed to find the Venue"
Exception: Failed to find the Venue
```

https://groups.google.com/a/mysociety.org/d/msg/cron-pombola/iYjHhE9LQqo/_BQ3kTZPBQAJ

**Comment by chrismytton** [comment]
Haven't seen this again, so I think it was a transient error.
