### ISSUE TITLE
[ZA] Missing WriteInPublic message causing 500 error

### ISSUE THREAD

**Issue by chrismytton** [mysociety/pombola#2589]
When you go to a message that doesn't exist, e.g. https://www.pa.org.za/write/message/394345345/, you get a 500 error, instead of a 404.

**Comment by chrismytton** [comment]
```
Internal Server Error: /write/message/394345345/
Traceback (most recent call last):
  File "/data/vhost/www.pa.org.za/pombola-virtualenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/vhost/www.pa.org.za/pombola-virtualenv/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/data/vhost/www.pa.org.za/pombola/pombola/writeinpublic/views.py", line 148, in dispatch
    return super(WriteInPublicMixin, self).dispatch(*args, **kwargs)
  File "/data/vhost/www.pa.org.za/pombola-virtualenv/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/data/vhost/www.pa.org.za/pombola-virtualenv/lib/python2.7/site-packages/django/views/generic/base.py", line 158, in get
    context = self.get_context_data(**kwargs)
  File "/data/vhost/www.pa.org.za/pombola/pombola/writeinpublic/views.py", line 243, in get_context_data
    context['message'] = self.client.get_message(self.kwargs['message_id'])
  File "/data/vhost/www.pa.org.za/pombola/pombola/writeinpublic/client.py", line 81, in get_message
    response.raise_for_status()
  File "/data/vhost/www.pa.org.za/pombola-virtualenv/lib/python2.7/site-packages/requests/models.py", line 834, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: NOT FOUND
```
