### ISSUE TITLE
[ZA] Error on place latlong page

### ISSUE THREAD

**Issue by chrismytton** [mysociety/pombola#2594]
Pages like https://www.pa.org.za/place/latlon/-29.681,30.947/ are currently returning a 500 error. The error is:

```
Internal Server Error: /place/latlon/-29.681,30.947/
Traceback (most recent call last):
  File "/data/vhost/www.pa.org.za/pombola-virtualenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/vhost/www.pa.org.za/pombola-virtualenv/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/data/vhost/www.pa.org.za/pombola-virtualenv/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/data/vhost/www.pa.org.za/pombola-virtualenv/lib/python2.7/site-packages/django/views/generic/detail.py", line 116, in get
    context = self.get_context_data(object=self.object)
  File "/data/vhost/www.pa.org.za/pombola/pombola/south_africa/views/geolocalization.py", line 156, in get_context_data
    context['ward_data'] = self.get_ward_councillors(self.location)
  File "/data/vhost/www.pa.org.za/pombola/pombola/south_africa/views/geolocalization.py", line 96, in get_ward_councillors
    mapit_json = r.json()
  File "/data/vhost/www.pa.org.za/pombola-virtualenv/lib/python2.7/site-packages/requests/models.py", line 802, in json
    return json.loads(self.text, **kwargs)
  File "/data/vhost/www.pa.org.za/pombola-virtualenv/lib/python2.7/site-packages/simplejson/__init__.py", line 505, in loads
    return _default_decoder.decode(s)
  File "/data/vhost/www.pa.org.za/pombola-virtualenv/lib/python2.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/data/vhost/www.pa.org.za/pombola-virtualenv/lib/python2.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by chrismytton** [comment]
This error is no longer occurring, so I think it must have been a transient issue with an external API.
