### ISSUE TITLE
[ZA] Cron error: Found organisations with multiple categories other than 'other'

### ISSUE THREAD

**Issue by chrismytton** [mysociety/pombola#2638]
> [cron-pombola] Cron <mzalendo-south-africa@dassie> run_management_command core_export_to_popolo_json /data/vhost/www.pa.org.za/media_root/popolo_json/ http://www.pa.org.za

```
There were 2 for organisation conduct-committee: set([u'education', u'political'])
Traceback (most recent call last):
  File "./manage.py", line 70, in <module>
    execute_from_command_line(sys.argv)
  File "/data/vhost/www.pa.org.za/pombola-virtualenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/data/vhost/www.pa.org.za/pombola-virtualenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/data/vhost/www.pa.org.za/pombola-virtualenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/data/vhost/www.pa.org.za/pombola-virtualenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/data/vhost/www.pa.org.za/pombola/pombola/core/management/commands/core_export_to_popolo_json.py", line 60, in handle
    inline_memberships=False
  File "/data/vhost/www.pa.org.za/pombola/pombola/core/popolo.py", line 366, in get_popolo_data
    result['organizations'] = get_organizations(primary_id_scheme, base_url)
  File "/data/vhost/www.pa.org.za/pombola/pombola/core/popolo.py", line 192, in get_organizations
    raise Exception, "Found organisations with multiple categories other than 'other'"
Exception: Found organisations with multiple categories other than 'other'
```

https://groups.google.com/a/mysociety.org/d/msg/cron-pombola/Dk2MEPyoQkU/JBI32GinAAAJ

**Comment by chrismytton** [comment]
The important bit here that I missed the first time I saw the stack trace is the first line:

> There were 2 for organisation conduct-committee: set([u'education', u'political'])
