### ISSUE TITLE
[ZA] Internal Server Error: /election/2019/provincial/north-west/

### ISSUE THREAD

**Issue by chrismytton** [mysociety/pombola#2642]
```
Internal Server Error: /election/2019/provincial/north-west/
Traceback (most recent call last):
  File "/data/vhost/www.pa.org.za/pombola-virtualenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/vhost/www.pa.org.za/pombola-virtualenv/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/data/vhost/www.pa.org.za/pombola-virtualenv/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/data/vhost/www.pa.org.za/pombola-virtualenv/lib/python2.7/site-packages/django/views/generic/base.py", line 158, in get
    context = self.get_context_data(**kwargs)
  File "/data/vhost/www.pa.org.za/pombola/pombola/south_africa/views/elections.py", line 308, in get_context_data
    slug=election_list.slug.replace(election_list_name, '')
  File "/data/vhost/www.pa.org.za/pombola-virtualenv/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/data/vhost/www.pa.org.za/pombola-virtualenv/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: Organisation matching query does not exist.
```

https://groups.google.com/a/mysociety.org/d/msg/cron-pa/JDp9RNOMcmI/a_vfSBGiBAAJ

**Comment by chrismytton** [comment]
This was because the RDPP organisation had the slug `rdpp1` rather than `rdpp`. I've now corrected that in the admin panel and this is working again.
