### ISSUE TITLE
Kenya: Cron error running update_hansard.bash

### ISSUE THREAD

**Issue by chrismytton** [mysociety/pombola#2680]
Seems that when we moved the site to a new server the other week we also caused pdftohtml to be updated, which is a problem for Kenya's Hansard parsing.

```
There was an exception when parsing <open file '/data/vhost/mzalendo.mysociety.org/hansard_cache/5/8/02385', mode 'r' at 0x7fb60d9a5390>
Traceback (most recent call last):
  File "./manage.py", line 70, in <module>
    execute_from_command_line(sys.argv)
  File "/data/vhost/mzalendo.mysociety.org/pombola-virtualenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/data/vhost/mzalendo.mysociety.org/pombola-virtualenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/data/vhost/mzalendo.mysociety.org/pombola-virtualenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/data/vhost/mzalendo.mysociety.org/pombola-virtualenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/data/vhost/mzalendo.mysociety.org/pombola-virtualenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 661, in handle
    return self.handle_noargs(**options)
  File "/data/vhost/mzalendo.mysociety.org/pombola/pombola/hansard/management/commands/hansard_process_sources.py", line 28, in handle_noargs
    html = KenyaParser.convert_pdf_to_html( pdf )
  File "/data/vhost/mzalendo.mysociety.org/pombola/pombola/hansard/kenya_parser.py", line 106, in convert_pdf_to_html
    output = cls.convert_pdf_to_html_local_machine( pdf_file )
  File "/data/vhost/mzalendo.mysociety.org/pombola/pombola/hansard/kenya_parser.py", line 131, in convert_pdf_to_html_local_machine
    raise Exception( "Bad pdftohtml version - got '%s' but want '%s'" % (version_error, wanted_version) )
Exception: Bad pdftohtml version - got 'pdftohtml version 0.48.0
Copyright 2005-2016 The Poppler Developers - http://poppler.freedesktop.org
Copyright 1999-2003 Gueorgui Ovtcharov and Rainer Dorsch
Copyright 1996-2011 Glyph & Cog, LLC

' but want 'pdftohtml version 0.18.4'
```

**Comment by chrismytton** [comment]
Fix for this is now live. I've manually re-run the Hansard parsing script, which appears to have worked, new entries have shown up on the site: https://info.mzalendo.com/hansard/. Thanks @crowbot for the fix!

For reference I had to blank the `last_processing_attempt` field to force a reparse:

```python
Source.objects
    .filter(date__gt=datetime.datetime(2019, 8, 1))
    .update(last_processing_attempt=None)
```
