### ISSUE TITLE
Error on MP attendance pages

### ISSUE THREAD

**Issue by chrismytton** [mysociety/pombola#2681]
We've been seeing the following error for a few weeks now on MP attendance pages. I haven't had time to look into it yet, but I wonder if it's related to the recent changes to that part of the site?

```
Internal Server Error: /mp-attendance/
Traceback (most recent call last):
  File "/data/vhost/www.pa.org.za/pombola-virtualenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/vhost/www.pa.org.za/pombola-virtualenv/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/data/vhost/www.pa.org.za/pombola-virtualenv/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/data/vhost/www.pa.org.za/pombola-virtualenv/lib/python2.7/site-packages/django/views/generic/base.py", line 158, in get
    context = self.get_context_data(**kwargs)
  File "/data/vhost/www.pa.org.za/pombola/pombola/south_africa/views/attendance.py", line 293, in get_context_data
    annual_attendance, context['party'], context['position'])
  File "/data/vhost/www.pa.org.za/pombola/pombola/south_africa/views/attendance.py", line 196, in filter_attendance
    if ctx_party and minister.parties()[0].slug.upper() != ctx_party:
  File "/data/vhost/www.pa.org.za/pombola-virtualenv/lib/python2.7/site-packages/django/db/models/query.py", line 201, in __getitem__
    return list(qs)[0]
IndexError: list index out of range
```

@xybrnet any ideas what might be happening here?

**Comment by xybrnet** [comment]
I had a quick look at this issue, and was able to resolve it.
https://github.com/mysociety/pombola/pull/2682

Some ministers are no longer members of parties, and we need to check for this before trying to access an element in the `parties` list.

**Comment by chrismytton** [comment]
Thanks for investigating this, @xybrnet! Fixed in https://github.com/mysociety/pombola/pull/2682
